# Generated by cpp11: do not edit by hand

del_rownames <- function(fr) {
  invisible(.Call(`_flowWorkspace_del_rownames`, fr))
}

set_rownames <- function(fr, val) {
  invisible(.Call(`_flowWorkspace_set_rownames`, fr, val))
}

get_rownames <- function(fr) {
  .Call(`_flowWorkspace_get_rownames`, fr)
}

backend_type <- function(fr) {
  .Call(`_flowWorkspace_backend_type`, fr)
}

cf_is_indexed <- function(fr) {
  .Call(`_flowWorkspace_cf_is_indexed`, fr)
}

cf_scale_time_channel_cpp <- function(fr) {
  invisible(.Call(`_flowWorkspace_cf_scale_time_channel_cpp`, fr))
}

cf_set_readonly <- function(fr, flag) {
  invisible(.Call(`_flowWorkspace_cf_set_readonly`, fr, flag))
}

cf_flush_meta_cpp <- function(fr) {
  invisible(.Call(`_flowWorkspace_cf_flush_meta_cpp`, fr))
}

cf_load_meta_cpp <- function(fr) {
  invisible(.Call(`_flowWorkspace_cf_load_meta_cpp`, fr))
}

get_uri <- function(fr) {
  .Call(`_flowWorkspace_get_uri`, fr)
}

realize_view_cytoframe <- function(fr, filename) {
  .Call(`_flowWorkspace_realize_view_cytoframe`, fr, filename)
}

copy_view_cytoframe <- function(fr) {
  .Call(`_flowWorkspace_copy_view_cytoframe`, fr)
}

subset_cytoframe_by_rows <- function(fr, idx) {
  invisible(.Call(`_flowWorkspace_subset_cytoframe_by_rows`, fr, idx))
}

subset_cytoframe_by_cols <- function(fr, idx) {
  invisible(.Call(`_flowWorkspace_subset_cytoframe_by_cols`, fr, idx))
}

frm_compensate <- function(fr, spillover) {
  invisible(.Call(`_flowWorkspace_frm_compensate`, fr, spillover))
}

write_to_disk <- function(fr, filename, ish5) {
  invisible(.Call(`_flowWorkspace_write_to_disk`, fr, filename, ish5))
}

load_cf <- function(url, readonly, on_disk) {
  .Call(`_flowWorkspace_load_cf`, url, readonly, on_disk)
}

cf_to_memcf <- function(fr) {
  .Call(`_flowWorkspace_cf_to_memcf`, fr)
}

setMarker <- function(fr, channel, marker) {
  invisible(.Call(`_flowWorkspace_setMarker`, fr, channel, marker))
}

set_all_channels <- function(fr, new_names) {
  invisible(.Call(`_flowWorkspace_set_all_channels`, fr, new_names))
}

setChannel <- function(fr, old, new_name) {
  invisible(.Call(`_flowWorkspace_setChannel`, fr, old, new_name))
}

get_channels <- function(fr) {
  .Call(`_flowWorkspace_get_channels`, fr)
}

append_cols <- function(fr, new_colnames, new_cols_mat) {
  invisible(.Call(`_flowWorkspace_append_cols`, fr, new_colnames, new_cols_mat))
}

parseFCS <- function(filename, configr, text_only, format, uri) {
  .Call(`_flowWorkspace_parseFCS`, filename, configr, text_only, format, uri)
}

cf_getData <- function(fr) {
  .Call(`_flowWorkspace_cf_getData`, fr)
}

cf_setData <- function(fr, rmat) {
  invisible(.Call(`_flowWorkspace_cf_setData`, fr, rmat))
}

cf_transform_data <- function(fr, translist) {
  invisible(.Call(`_flowWorkspace_cf_transform_data`, fr, translist))
}

cf_getKeyword <- function(fr, key) {
  .Call(`_flowWorkspace_cf_getKeyword`, fr, key)
}

cf_getKeywords <- function(fr) {
  .Call(`_flowWorkspace_cf_getKeywords`, fr)
}

cf_setKeywords <- function(fr, keys) {
  invisible(.Call(`_flowWorkspace_cf_setKeywords`, fr, keys))
}

cf_setKeywordsSubset <- function(fr, keys, values) {
  invisible(.Call(`_flowWorkspace_cf_setKeywordsSubset`, fr, keys, values))
}

cf_renameKeywords <- function(fr, old_keys, new_keys) {
  invisible(.Call(`_flowWorkspace_cf_renameKeywords`, fr, old_keys, new_keys))
}

cf_removeKeywords <- function(fr, keys) {
  invisible(.Call(`_flowWorkspace_cf_removeKeywords`, fr, keys))
}

getncol <- function(fr) {
  .Call(`_flowWorkspace_getncol`, fr)
}

getnrow <- function(fr) {
  .Call(`_flowWorkspace_getnrow`, fr)
}

setpdata <- function(fr, df) {
  invisible(.Call(`_flowWorkspace_setpdata`, fr, df))
}

getpdata <- function(fr) {
  .Call(`_flowWorkspace_getpdata`, fr)
}

cs_set_compensation <- function(cs, comps, compensate_data) {
  invisible(.Call(`_flowWorkspace_cs_set_compensation`, cs, comps, compensate_data))
}

set_cytoframe <- function(cs, sn, fr) {
  invisible(.Call(`_flowWorkspace_set_cytoframe`, cs, sn, fr))
}

add_cytoframe <- function(cs, sn, fr) {
  invisible(.Call(`_flowWorkspace_add_cytoframe`, cs, sn, fr))
}

new_cytoset <- function() {
  .Call(`_flowWorkspace_new_cytoset`)
}

fcs_to_cytoset <- function(files, rconfig, backend, backend_dir) {
  .Call(`_flowWorkspace_fcs_to_cytoset`, files, rconfig, backend, backend_dir)
}

get_colnames <- function(cs) {
  .Call(`_flowWorkspace_get_colnames`, cs)
}

realize_view_cytoset <- function(cs, path) {
  .Call(`_flowWorkspace_realize_view_cytoset`, cs, path)
}

copy_view_cytoset <- function(cs) {
  .Call(`_flowWorkspace_copy_view_cytoset`, cs)
}

subset_cytoset_by_rows <- function(cs, sn, idx) {
  invisible(.Call(`_flowWorkspace_subset_cytoset_by_rows`, cs, sn, idx))
}

subset_cytoset <- function(cs, sample_uids, ch_selected) {
  invisible(.Call(`_flowWorkspace_subset_cytoset`, cs, sample_uids, ch_selected))
}

get_cytoframe <- function(cs, sample_uid, ch_selected) {
  .Call(`_flowWorkspace_get_cytoframe`, cs, sample_uid, ch_selected)
}

set_pheno_data <- function(cs, value) {
  invisible(.Call(`_flowWorkspace_set_pheno_data`, cs, value))
}

get_pheno_data <- function(cs) {
  .Call(`_flowWorkspace_get_pheno_data`, cs)
}

getDescendants_cpp <- function(gsPtr, sampleName, node) {
  .Call(`_flowWorkspace_getDescendants_cpp`, gsPtr, sampleName, node)
}

getPopCounts_cpp <- function(gs, freq, subpopulation, flowJo, isFullPath) {
  .Call(`_flowWorkspace_getPopCounts_cpp`, gs, freq, subpopulation, flowJo, isFullPath)
}

cpp_getSingleCellExpressionByGate <- function(gs, sampleName, markers_pops, data, markers, threshold) {
  .Call(`_flowWorkspace_cpp_getSingleCellExpressionByGate`, gs, sampleName, markers_pops, data, markers, threshold)
}

cpp_getSingleCellExpression <- function(gs, sampleName, pops, data, markers, threshold) {
  .Call(`_flowWorkspace_cpp_getSingleCellExpression`, gs, sampleName, pops, data, markers, threshold)
}

h5_set_error_handler <- function() {
  invisible(.Call(`_flowWorkspace_h5_set_error_handler`))
}

gen_uid <- function() {
  .Call(`_flowWorkspace_gen_uid`)
}

getSplineCoefs <- function(channelRange, maxValue, pos, neg, widthBasis, inverse) {
  .Call(`_flowWorkspace_getSplineCoefs`, channelRange, maxValue, pos, neg, widthBasis, inverse)
}

updateChannels_cpp <- function(gsPtr, map) {
  invisible(.Call(`_flowWorkspace_updateChannels_cpp`, gsPtr, map))
}

cpp_plotGh <- function(gs, sampleName, output) {
  invisible(.Call(`_flowWorkspace_cpp_plotGh`, gs, sampleName, output))
}

cpp_getNodes <- function(gs, sampleName, order, fullPath, showHidden) {
  .Call(`_flowWorkspace_cpp_getNodes`, gs, sampleName, order, fullPath, showHidden)
}

getNodePath <- function(gs, sampleName, id) {
  .Call(`_flowWorkspace_getNodePath`, gs, sampleName, id)
}

cpp_getNodeID <- function(gs, sampleName, gatePath) {
  .Call(`_flowWorkspace_cpp_getNodeID`, gs, sampleName, gatePath)
}

cpp_getParent <- function(gs, sampleName, gatePath) {
  .Call(`_flowWorkspace_cpp_getParent`, gs, sampleName, gatePath)
}

cpp_getChildren <- function(gs, sampleName, gatePath, showHidden) {
  .Call(`_flowWorkspace_cpp_getChildren`, gs, sampleName, gatePath, showHidden)
}

cpp_getPopStats <- function(gs, sampleName, gatePath) {
  .Call(`_flowWorkspace_cpp_getPopStats`, gs, sampleName, gatePath)
}

cpp_getCompensation <- function(gs, sampleName) {
  .Call(`_flowWorkspace_cpp_getCompensation`, gs, sampleName)
}

set_transformations <- function(gs, sampleName, translist) {
  invisible(.Call(`_flowWorkspace_set_transformations`, gs, sampleName, translist))
}

cpp_getTransformations <- function(gs, sampleName, inverse) {
  .Call(`_flowWorkspace_cpp_getTransformations`, gs, sampleName, inverse)
}

cpp_getGate <- function(gs, sampleName, gatePath) {
  .Call(`_flowWorkspace_cpp_getGate`, gs, sampleName, gatePath)
}

cpp_getIndices <- function(gs, sampleName, gatePath) {
  .Call(`_flowWorkspace_cpp_getIndices`, gs, sampleName, gatePath)
}

cpp_setIndices <- function(gs, sampleName, u, ind) {
  invisible(.Call(`_flowWorkspace_cpp_setIndices`, gs, sampleName, u, ind))
}

cpp_getGateFlag <- function(gs, sampleName, gatePath) {
  .Call(`_flowWorkspace_cpp_getGateFlag`, gs, sampleName, gatePath)
}

cpp_getNegateFlag <- function(gs, sampleName, gatePath) {
  .Call(`_flowWorkspace_cpp_getNegateFlag`, gs, sampleName, gatePath)
}

cpp_getHiddenFlag <- function(gs, sampleName, gatePath) {
  .Call(`_flowWorkspace_cpp_getHiddenFlag`, gs, sampleName, gatePath)
}

cpp_addGate <- function(gs, sampleName, filter, gatePath, popName) {
  .Call(`_flowWorkspace_cpp_addGate`, gs, sampleName, filter, gatePath, popName)
}

cpp_boolGating <- function(gs, sampleName, filter, nodeID) {
  invisible(.Call(`_flowWorkspace_cpp_boolGating`, gs, sampleName, filter, nodeID))
}

set_quadgate <- function(gs, sampleName, gatePath, inter) {
  invisible(.Call(`_flowWorkspace_set_quadgate`, gs, sampleName, gatePath, inter))
}

cpp_setGate <- function(gs, sampleName, gatePath, filter) {
  invisible(.Call(`_flowWorkspace_cpp_setGate`, gs, sampleName, gatePath, filter))
}

cpp_removeNode <- function(gs, sampleName, gatePath, recursive) {
  invisible(.Call(`_flowWorkspace_cpp_removeNode`, gs, sampleName, gatePath, recursive))
}

moveNode <- function(gsPtr, sampleName, node, parent) {
  invisible(.Call(`_flowWorkspace_moveNode`, gsPtr, sampleName, node, parent))
}

setNodeName <- function(gs, sampleName, gatePath, newNodeName) {
  invisible(.Call(`_flowWorkspace_setNodeName`, gs, sampleName, gatePath, newNodeName))
}

setNodeFlag <- function(gs, sampleName, gatePath, hidden) {
  invisible(.Call(`_flowWorkspace_setNodeFlag`, gs, sampleName, gatePath, hidden))
}

gs_transform_data <- function(gsPtr) {
  invisible(.Call(`_flowWorkspace_gs_transform_data`, gsPtr))
}

cpp_gating <- function(gsPtr, nodes, alwaysLoadData, verbose, leafbool) {
  invisible(.Call(`_flowWorkspace_cpp_gating`, gsPtr, nodes, alwaysLoadData, verbose, leafbool))
}

subset_gs_by_sample <- function(gsPtr, samples) {
  .Call(`_flowWorkspace_subset_gs_by_sample`, gsPtr, samples)
}

get_cytoset <- function(gsPtr) {
  .Call(`_flowWorkspace_get_cytoset`, gsPtr)
}

get_cytoset_from_node <- function(gsPtr, node) {
  .Call(`_flowWorkspace_get_cytoset_from_node`, gsPtr, node)
}

set_cytoset <- function(gsPtr, cs) {
  invisible(.Call(`_flowWorkspace_set_cytoset`, gsPtr, cs))
}

cpp_getSamples <- function(gsPtr) {
  .Call(`_flowWorkspace_cpp_getSamples`, gsPtr)
}

cpp_NewGatingSet <- function(gsPtr, src_sample_uid, cs, execute, comp_source) {
  .Call(`_flowWorkspace_cpp_NewGatingSet`, gsPtr, src_sample_uid, cs, execute, comp_source)
}

get_gatingset_id <- function(gsPtr) {
  .Call(`_flowWorkspace_get_gatingset_id`, gsPtr)
}

set_gatingset_id <- function(gsPtr, id) {
  invisible(.Call(`_flowWorkspace_set_gatingset_id`, gsPtr, id))
}

cpp_saveGatingSet <- function(gs, path, backend_opt) {
  invisible(.Call(`_flowWorkspace_cpp_saveGatingSet`, gs, path, backend_opt))
}

cpp_loadGatingSet <- function(path, readonly, select_samples, verbose) {
  .Call(`_flowWorkspace_cpp_loadGatingSet`, path, readonly, select_samples, verbose)
}

load_legacy_gs <- function(pbfile, cs) {
  .Call(`_flowWorkspace_load_legacy_gs`, pbfile, cs)
}

cpp_CloneGatingSet <- function(gs, h5_dir, is_copy_data) {
  .Call(`_flowWorkspace_cpp_CloneGatingSet`, gs, h5_dir, is_copy_data)
}

cpp_combineGatingSet <- function(gsList, sampleList) {
  .Call(`_flowWorkspace_cpp_combineGatingSet`, gsList, sampleList)
}

cpp_setSample <- function(gs, oldName, newName) {
  invisible(.Call(`_flowWorkspace_cpp_setSample`, gs, oldName, newName))
}

is_tiledb_support <- function() {
  .Call(`_flowWorkspace_is_tiledb_support`)
}

cpp_getLogLevel <- function() {
  .Call(`_flowWorkspace_cpp_getLogLevel`)
}

cpp_setLogLevel <- function(loglevel) {
  invisible(.Call(`_flowWorkspace_cpp_setLogLevel`, loglevel))
}

cpp_togleErrorFlag <- function() {
  invisible(.Call(`_flowWorkspace_cpp_togleErrorFlag`))
}

setCounts_cpp <- function(gsPtr, sampleName, node, count) {
  invisible(.Call(`_flowWorkspace_setCounts_cpp`, gsPtr, sampleName, node, count))
}
