# Generated by cpp11: do not edit by hand

del_rownames <- function(fr) {
  invisible(.Call(`_flowWorkspace_del_rownames`, fr))
}

set_rownames <- function(fr, val) {
  invisible(.Call(`_flowWorkspace_set_rownames`, fr, val))
}

get_rownames <- function(fr) {
  .Call(`_flowWorkspace_get_rownames`, fr)
}

backend_type <- function(fr) {
  .Call(`_flowWorkspace_backend_type`, fr)
}

cf_is_indexed <- function(fr) {
  .Call(`_flowWorkspace_cf_is_indexed`, fr)
}

cf_scale_time_channel_cpp <- function(fr) {
  invisible(.Call(`_flowWorkspace_cf_scale_time_channel_cpp`, fr))
}

cf_set_readonly <- function(fr, flag) {
  invisible(.Call(`_flowWorkspace_cf_set_readonly`, fr, flag))
}

cf_flush_meta_cpp <- function(fr) {
  invisible(.Call(`_flowWorkspace_cf_flush_meta_cpp`, fr))
}

cf_load_meta_cpp <- function(fr) {
  invisible(.Call(`_flowWorkspace_cf_load_meta_cpp`, fr))
}

get_uri <- function(fr) {
  .Call(`_flowWorkspace_get_uri`, fr)
}

realize_view_cytoframe <- function(fr, filename) {
  .Call(`_flowWorkspace_realize_view_cytoframe`, fr, filename)
}

copy_view_cytoframe <- function(fr) {
  .Call(`_flowWorkspace_copy_view_cytoframe`, fr)
}

subset_cytoframe_by_rows <- function(fr, idx) {
  invisible(.Call(`_flowWorkspace_subset_cytoframe_by_rows`, fr, idx))
}

subset_cytoframe_by_cols <- function(fr, idx) {
  invisible(.Call(`_flowWorkspace_subset_cytoframe_by_cols`, fr, idx))
}

frm_compensate <- function(fr, spillover) {
  invisible(.Call(`_flowWorkspace_frm_compensate`, fr, spillover))
}

write_to_disk <- function(fr, filename, ish5) {
  invisible(.Call(`_flowWorkspace_write_to_disk`, fr, filename, ish5))
}

load_cf <- function(url, readonly, on_disk) {
  .Call(`_flowWorkspace_load_cf`, url, readonly, on_disk)
}

cf_to_memcf <- function(fr) {
  .Call(`_flowWorkspace_cf_to_memcf`, fr)
}

setMarker <- function(fr, channel, marker) {
  invisible(.Call(`_flowWorkspace_setMarker`, fr, channel, marker))
}

set_all_channels <- function(fr, new_names) {
  invisible(.Call(`_flowWorkspace_set_all_channels`, fr, new_names))
}

setChannel <- function(fr, old, new_name) {
  invisible(.Call(`_flowWorkspace_setChannel`, fr, old, new_name))
}

get_channels <- function(fr) {
  .Call(`_flowWorkspace_get_channels`, fr)
}

append_cols <- function(fr, new_colnames, new_cols_mat) {
  .Call(`_flowWorkspace_append_cols`, fr, new_colnames, new_cols_mat)
}

cf_getData <- function(fr) {
  .Call(`_flowWorkspace_cf_getData`, fr)
}

cf_setData <- function(fr, rmat) {
  invisible(.Call(`_flowWorkspace_cf_setData`, fr, rmat))
}

cf_transform_data <- function(fr, translist) {
  invisible(.Call(`_flowWorkspace_cf_transform_data`, fr, translist))
}
